<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="8" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="89" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
    <groups>
      <group name="smoke">
        <method signature="Testing3.mainTest()[pri:2, instance:com.testing.Testing3@3bfdc050]" name="mainTest" class="com.testing.Testing3"/>
      </group> <!-- smoke -->
      <group name="xyz">
        <method signature="Testing3.endTest()[pri:3, instance:com.testing.Testing3@3bfdc050]" name="endTest" class="com.testing.Testing3"/>
      </group> <!-- xyz -->
      <group name="sanity">
        <method signature="Testing3.mainTest()[pri:2, instance:com.testing.Testing3@3bfdc050]" name="mainTest" class="com.testing.Testing3"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Test" duration-ms="89" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
      <class name="com.testing.Testing3">
        <test-method status="PASS" signature="homeTest()[pri:1, instance:com.testing.Testing3@3bfdc050]" name="homeTest" duration-ms="5" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homeTest -->
        <test-method status="FAIL" signature="mainTest()[pri:2, instance:com.testing.Testing3@3bfdc050]" name="mainTest" duration-ms="3" started-at="2020-01-24T15:11:56Z" depends-on-methods="com.testing.Testing3.homeTest" finished-at="2020-01-24T15:11:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Verifying Element expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Verifying Element expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.testing.Testing3.mainTest(Testing3.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mainTest -->
        <test-method status="SKIP" signature="endTest()[pri:3, instance:com.testing.Testing3@3bfdc050]" name="endTest" duration-ms="0" started-at="2020-01-24T15:11:56Z" depends-on-methods="com.testing.Testing3.mainTest, com.testing.Testing3.homeTest" finished-at="2020-01-24T15:11:56Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Testing3.endTest()[pri:3, instance:com.testing.Testing3@3bfdc050] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Testing3.endTest()[pri:3, instance:com.testing.Testing3@3bfdc050] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.testing.Testing3 -->
      <class name="com.testing.Testing1">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="beforeSuite" is-config="true" duration-ms="33" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="beforeTest" is-config="true" duration-ms="3" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="beforeClass" is-config="true" duration-ms="0" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="test1()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="test1" duration-ms="6" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping this exception
at com.testing.Testing1.test1(Testing1.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="afterMethod" is-config="true" duration-ms="1" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test2()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="test2" duration-ms="2" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="afterMethod" is-config="true" duration-ms="1" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="test3()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="test3" duration-ms="1" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="afterMethod" is-config="true" duration-ms="1" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="afterClass" is-config="true" duration-ms="0" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="afterTest" is-config="true" duration-ms="1" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.testing.Testing1@1e88b3c]" name="afterSuite" is-config="true" duration-ms="1" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.testing.Testing1 -->
      <class name="com.testing.Testing2">
        <test-method status="PASS" signature="test4()[pri:0, instance:com.testing.Testing2@42d80b78]" name="test4" duration-ms="4" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="PASS" signature="test5()[pri:0, instance:com.testing.Testing2@42d80b78]" name="test5" duration-ms="2" started-at="2020-01-24T15:11:56Z" finished-at="2020-01-24T15:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
      </class> <!-- com.testing.Testing2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
